# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GirisEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_girisekrani(object):
    def setupUi(self, girisekrani):
        girisekrani.setObjectName("girisekrani")
        girisekrani.resize(893, 703)
        self.centralwidget = QtWidgets.QWidget(girisekrani)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 320, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 400, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lneusername = QtWidgets.QLineEdit(self.centralwidget)
        self.lneusername.setGeometry(QtCore.QRect(420, 340, 201, 41))
        self.lneusername.setObjectName("lneusername")
        self.lnepassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lnepassword.setGeometry(QtCore.QRect(420, 420, 201, 41))
        self.lnepassword.setObjectName("lnepassword")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(300, 40, 301, 201))
        self.textBrowser.setObjectName("textBrowser")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(370, 490, 131, 51))
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(370, 570, 131, 51))
        self.btnRegister.setObjectName("btnRegister")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 620, 231, 31))
        self.label_3.setObjectName("label_3")
        girisekrani.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(girisekrani)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 26))
        self.menubar.setObjectName("menubar")
        girisekrani.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(girisekrani)
        self.statusbar.setObjectName("statusbar")
        girisekrani.setStatusBar(self.statusbar)

        self.retranslateUi(girisekrani)
        QtCore.QMetaObject.connectSlotsByName(girisekrani)

    def retranslateUi(self, girisekrani):
        _translate = QtCore.QCoreApplication.translate
        girisekrani.setWindowTitle(_translate("girisekrani", "MainWindow"))
        self.label.setText(_translate("girisekrani", "Kullanıcı Adı"))
        self.label_2.setText(_translate("girisekrani", "Şifre"))
        self.textBrowser.setHtml(_translate("girisekrani", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt;\">Giriş Ekranı</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnLogin.setText(_translate("girisekrani", "Giriş Yap"))
        self.btnRegister.setText(_translate("girisekrani", "Kayıt Ol"))
        self.label_3.setText(_translate("girisekrani", "Hesabın Yok Mu? Hemen Kayıt Ol!"))
