# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1050, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tblListe = QtWidgets.QTableWidget(self.centralwidget)
        self.tblListe.setGeometry(QtCore.QRect(251, 200, 571, 361))
        self.tblListe.setRowCount(30)
        self.tblListe.setColumnCount(7)
        self.tblListe.setObjectName("tblListe")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(251, 170, 141, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(391, 161, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(591, 157, 211, 41))
        self.pushButton.setObjectName("pushButton")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(771, 650, 91, 61))
        self.btnBack.setStyleSheet("")
        self.btnBack.setObjectName("btnBack")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(241, 580, 101, 41))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 583, 311, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 580, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(350, 30, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border : 1px solid black")
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kategoriye Göre Listele"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Antienfeksiyon İlaçları"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Antineoplastik İlaçları"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hormon İlaçları"))
        self.comboBox.setItemText(3, _translate("MainWindow", "İmmun Sistem İlaçları"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Kalp ve Damar Hast. İlaçları"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Kan İlaçları"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Kulağa Göze Buruna Etki Eden İlaçlar."))
        self.comboBox.setItemText(7, _translate("MainWindow", "Merkezi Sinir Sistemi İlaçları"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Mide ve Bağırsağa Etki Eden İlaçlar"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Muhtelif İlaç Kategorileri"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Otonom Sinir Sistemine Etkili İlaçlar"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Sıvıya ve Elektrolite Etki Eden İlaçlar"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Solunum Yollarına Etki Eden İlaçlar"))
        self.pushButton.setText(_translate("MainWindow", "Listele"))
        self.btnBack.setText(_translate("MainWindow", "Geri"))
        self.label_2.setText(_translate("MainWindow", "İsime Göre Listele"))
        self.pushButton_2.setText(_translate("MainWindow", "Bütün Ürünleri Listele"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kullanıcı Ekranı</p></body></html>"))
